### ISSUE TITLE
[Build]完善基础控制页面----1

### ISSUE THREAD

**Issue by solawc** [solawc/ESP32_LCD_PICO#6]
1、完成好控制界面
2、完成好工界面
3、实现主题切换功能

**Comment by kweilim98** [comment]
这个是给与mks dlc32页面的吗？

**Comment by solawc** [comment]
> 这个是给与mks dlc32页面的吗？

这也许会用在DLC32上，但首先应该是用于一个连接DLC32的串口屏上。并且它还会兼容Marlin

**Comment by kweilim98** [comment]
可以加微信号吗？

**Comment by solawc** [comment]
> 可以加微信号吗？

1225093964
